name: eservices
version: 1.0.5+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:

  cupertino_icons:

  get: # for state managment and context less stuff
  logger: # log events in clear way insted of (print)
  flutter_screenutil: # make app responsive
  get_storage: # shared preferences replacement (sync)
  hand_signature: # for user hand signature easy
  image_picker: # pick an image from gallery or camera
  image_cropper: # crop your image
  dotted_border: # Dotted Border
  flutter_staggered_animations: # Animated Grid View
  timelines: # list of timeline
  flutter_widget_from_html: # render html to flutter widget

  flutter:
    sdk: flutter
  dio: ^5.6.0
  pretty_dio_logger: ^1.2.0-beta-1
  path_provider: ^2.0.11
  font_awesome_flutter: ^10.3.0
  open_app_file: ^4.0.1
  qr_flutter: ^4.1.0
  share_plus: ^7.0.2
  image_gallery_saver: ^2.0.3
  zoom_widget: ^2.0.1
  pdf: ^3.10.4
  badges: ^3.1.2
  signalr_core: ^1.1.1
  uuid: ^4.2.2
  webview_flutter: ^3.0.4
  timeline_list: ^0.0.6
  upgrader: ^10.2.0
  mobile_scanner: ^4.0.1
  infinite_scroll_pagination: ^4.0.0
  flutter_cached_pdfview: ^0.4.2
  cached_network_image: ^3.3.1
  permission_handler: ^11.3.1
  flutter_quill: ^10.1.9
  delta_to_html: ^0.2.2
  file_picker: ^8.0.7
  tap_to_expand: ^0.7.2
  animated_rating_stars: ^1.0.1
  url_launcher: ^6.1.5
  newton_particles: ^0.1.8
  lottie: ^3.1.3
  html: ^0.15.4

dev_dependencies:
  flutter_lints:
  build_runner:  # generate dart files
  flutter_launcher_icons: "^0.13.1"

  flutter_test:
    sdk: flutter


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: NeoSans-AR
      fonts:
        - asset: assets/fonts/Montserrat-Arabic-Regular.ttf
    - family: NeoSans
      fonts:
        - asset: assets/fonts/Cairo-SemiBold.ttf
        - asset: assets/fonts/Cairo-Black.ttf
    - family: AL-MOHANAD_BOLD
      fonts:
        - asset: assets/fonts/AL-MOHANAD_BOLD.ttf
    - family: TraditionalArabic
      fonts:
        - asset: assets/fonts/Traditional-Arabic.ttf
        - asset: assets/fonts/Traditional-Arabic-Bold.ttf